### ISSUE TITLE
Cannot be unpacked on Windows

### ISSUE THREAD

**Issue by chorny** [stevieb9/rpi-dac-mcp4922#1]
This distribution contains file that cannot be unpacked on Windows: "docs/datasheet/mcp48**.pdf".

**Comment by stevieb9** [comment]
Thank you for the report. I will do some testing on Windows this afternoon.

Steve

**Comment by stevieb9** [comment]
2.36.1 pushed to the CPAN (version change to reflect the fact it relies on wiringPi version 2.36+)
